const emailLink = '<a href="mailto:info@q-strata.com">info@q-strata.com</a>';

const interiorHero = (label, title, summary) => `
  <section class="interior-hero">
    <div class="page-width">
      <p class="breadcrumbs"><a href="../">Home</a> / ${label}</p>
      <h1>${title}</h1>
      <p class="hero-summary">${summary}</p>
    </div>
  </section>`;

const closingCTA = () => `
  <section class="closing-cta">
    <div class="page-width cta-inner">
      <div><p class="eyebrow">Bring Us the Decision in Front of You.</p><h2>Let’s Turn Complexity Into a Clear Next Move.</h2></div>
      <a class="button button-light" href="../contact/">Start a Conversation →</a>
    </div>
  </section>`;

const cards = (items, className = "capability-grid") => `
  <div class="${className}">${items.map(([title, copy], index) => `
    <article class="capability-item"><span class="number">0${index + 1}</span><h2>${title}</h2><p>${copy}</p></article>`).join("")}
  </div>`;

const home = `
  <section class="brand-banner" aria-label="Quant Strata Business Advisory and Analytics in Philadelphia">
    <img src="./assets/quant-strata-philadelphia-banner.webp" width="2048" height="1152" alt="Quant Strata Business Advisory and Analytics with the Philadelphia skyline" fetchpriority="high" decoding="async">
  </section>
  <section class="hero">
    <div class="hero-grid page-width">
      <div class="hero-copy">
        <p class="eyebrow">Business Advisory · Analytics · Philadelphia</p>
        <h1>Clarity for the Numbers.<span> Intelligence for the Decision.</span></h1>
        <p class="hero-lede">Quant Strata connects finance, accounting operations, and advanced analytics so leaders can understand performance, strengthen compliance, and move forward with evidence.</p>
        <div class="hero-actions"><a class="button button-primary" href="./contact/">Start a Conversation →</a><a class="button button-ghost" href="./services/">Explore Our Services</a></div>
        <div class="credibility-line"><span>◆ Veteran & Minority-Owned</span><span>◆ 15+ Years of Experience</span></div>
      </div>
      <div class="decision-panel" aria-label="Illustrative Executive Decision Dashboard">
        <div class="panel-topline"><div><p>Decision System</p><strong>Executive View</strong></div><span class="live-pill"><i></i> Integrated</span></div>
        <div class="metric-row"><div><span>Financial</span><strong>Actuals</strong><small>Clear Close</small></div><div><span>Forward</span><strong>Forecast</strong><small>Scenario Ready</small></div><div><span>Control</span><strong>Governance</strong><small>Documented</small></div></div>
        <div class="chart-card"><div class="chart-label"><span>Performance Signal</span><small>Plan vs. Outlook</small></div><div class="mini-chart"><i class="line"></i><i class="plan-line"></i></div><div class="legend"><span><i class="cyan-dot"></i>Outlook</span><span><i class="gold-dot"></i>Plan</span></div></div>
        <div class="panel-footer">Finance + Operations + Data, Aligned in One View</div>
      </div>
    </div>
  </section>
  <section class="proof-band"><div class="page-width proof-grid"><p>Built for Organizations Where the Quality of the Decision Matters.</p><div><strong>Private</strong><span>Enterprise</span></div><div><strong>Public</strong><span>Institutions</span></div><div><strong>Mission</strong><span>Driven</span></div></div></section>
  <section class="section page-width">
    <div class="section-heading split-heading"><div><p class="eyebrow dark">Two Disciplines. One Operating View.</p><h2>Advisory Depth Meets Analytical Precision.</h2></div><p>Engage Quant Strata for a focused project or combine capabilities into an ongoing decision-support partnership.</p></div>
    <div class="pathway-grid">
      <article class="pathway-card advisory-card"><div class="pathway-icon">QS</div><p class="card-kicker">Business Advisory</p><h3>Stronger Finance Operations and Clearer Accountability.</h3><p>Practical support that helps leadership improve reporting, planning, compliance, and the financial processes behind daily operations.</p><ul><li>Accounting Operations and Management Reporting</li><li>FP&amp;A, Cash-Flow Forecasting, and Scenario Planning</li><li>Nonprofit Formation and Compliance Support</li><li>Controls, Documentation, and Audit Readiness</li></ul><a href="./business-advisory/">Explore Business Advisory →</a></article>
      <article class="pathway-card analytics-card"><div class="pathway-icon">BI</div><p class="card-kicker">Analytics & Technology</p><h3>Data Translated Into Decisions Leaders Can Defend.</h3><p>Advanced models, dashboards, and integrated reporting that turn complex information into a trusted management resource.</p><ul><li>Executive Dashboards and KPI Architecture</li><li>Predictive, Statistical, and Financial Modeling</li><li>Data Integration, Automation, and Reporting</li><li>Economic, Market, and Geospatial Analysis</li></ul><a href="./analytics-technology/">Explore Analytics & Technology →</a></article>
    </div>
  </section>
  <section class="section sectors-section"><div class="page-width"><div class="section-heading centered-heading"><p class="eyebrow dark">Who We Serve</p><h2>Experience Across Commercial, Public, and Mission-Driven Organizations.</h2></div><div class="sector-grid"><article class="sector-card"><h3>Businesses & Contractors</h3><p>Finance infrastructure, management insight, and scalable reporting for organizations ready to operate with greater control.</p></article><article class="sector-card"><h3>Government & Institutions</h3><p>Transparent analysis, performance measurement, and decision support for public and regulated environments.</p></article><article class="sector-card"><h3>Nonprofits & Associations</h3><p>Formation, reporting, governance, and analytics support designed around mission, accountability, and compliance.</p></article></div></div></section>
  <section class="section page-width operating-section"><div class="operating-copy"><p class="eyebrow dark">The Quant Strata Approach</p><h2>Start With the Business Question—Not the Software.</h2><p>We define the decision, establish what reliable evidence looks like, and build the analysis or operating process around the people who must use it.</p><a class="text-link" href="./about/">About Quant Strata →</a></div><ol class="process-list"><li><span>01</span><div><strong>Diagnose</strong><p>Clarify the decision, constraint, stakeholders, and required outcome.</p></div></li><li><span>02</span><div><strong>Design</strong><p>Define the reporting, controls, model, or analytical solution.</p></div></li><li><span>03</span><div><strong>Deliver</strong><p>Implement a practical resource your team can understand and maintain.</p></div></li><li><span>04</span><div><strong>Strengthen</strong><p>Measure adoption, refine the process, and support the next decision.</p></div></li></ol></section>
  <section class="closing-cta"><div class="page-width cta-inner"><div><p class="eyebrow">Bring Us the Decision in Front of You.</p><h2>Let’s Turn Complexity Into a Clear Next Move.</h2></div><a class="button button-light" href="./contact/">Start a Conversation →</a></div></section>`;

const businessAdvisory = `${interiorHero("Business Advisory", "Financial Operations Built for Control, Insight, and Growth.", "Quant Strata helps businesses and nonprofit organizations strengthen the processes behind accounting, planning, compliance, and management decision-making.")}
  <section class="interior-section page-width"><div class="interior-intro"><h2>Practical Support for the Work Behind the Numbers.</h2><p>Our advisory work connects accurate financial information with disciplined operating processes. The goal is not simply to produce reports—it is to help leadership understand what is happening, prepare for what is next, and maintain documentation that stands up to review.</p></div>${cards([["Accounting Operations","Month-end close support, reconciliations, financial schedules, management reporting, and process documentation."],["FP&A and Decision Support","Budgets, forecasts, cash-flow planning, performance analysis, and scenarios that give leadership a forward view."],["Fractional Finance Support","Flexible controller-level support and financial operating discipline without the cost of a full internal department."],["Tax-Ready Organization","Clean records, organized documentation, schedules, and coordination support that prepare the business for its licensed tax professional."],["Nonprofit Compliance","Formation and exemption-application support, annual reporting preparation, governance policies, and compliance calendars."],["Controls and Readiness","Internal-control documentation, policy development, audit-preparedness support, and remediation planning."]])}</section>
  <section class="interior-section tinted"><div class="page-width"><div class="interior-intro"><h2>Engagements Shaped Around the Organization.</h2><p>Support may be delivered as a defined project, a recurring monthly engagement, or a broader advisory relationship aligned with management’s priorities and internal capacity.</p></div><ul class="deliverables"><li>Accounting Close and Reporting Packages</li><li>Budget and Rolling-Forecast Models</li><li>Cash-Flow and Scenario Planning</li><li>Policies and Process Documentation</li><li>Nonprofit Formation and Annual Compliance Support</li><li>Audit and Tax-Preparation Readiness Schedules</li></ul></div></section>${closingCTA()}`;

const analytics = `${interiorHero("Analytics & Technology", "Turn Complex Data Into a Trusted Management Resource.", "From executive dashboards to advanced quantitative models, Quant Strata builds analytical systems around the decision your organization needs to make.")}
  <section class="interior-section page-width"><div class="interior-intro"><h2>Technology Should Make the Answer Clearer.</h2><p>We combine business context, quantitative rigor, and clear visualization. Every solution is designed to improve how information moves—from the underlying source through analysis and into the hands of the people accountable for action.</p></div>${cards([["Executive Dashboards","KPI frameworks and leadership dashboards in Power BI, Tableau, Qlik, and tailored web applications."],["Forecasting and Modeling","Statistical, financial, predictive, optimization, and scenario models that support defensible decisions."],["Data Integration","Connected reporting across finance, HR, procurement, operations, and external data sources."],["Automation","Repeatable reporting pipelines and analytical workflows that reduce manual effort and improve consistency."],["Economic and Market Analysis","Market sizing, competitive research, feasibility studies, program evaluation, and economic analysis."],["GIS and Location Intelligence","Geospatial analysis, mapping, site assessment, catchment studies, and location-based decision support."]])}</section>
  <section class="interior-section tinted"><div class="page-width"><div class="interior-intro"><h2>Tools Selected for the Problem.</h2><p>Our experience spans modern business intelligence, programming, modeling, data engineering, and cloud environments.</p></div><ul class="deliverables"><li>Power BI, Tableau, and Qlik Dashboards</li><li>R, Python, SQL, and Statistical Modeling</li><li>Financial and Operational Forecasting</li><li>Automated Management Reporting</li><li>Cloud and Database Integration</li><li>Executive-Ready Visual Communication</li></ul></div></section>${closingCTA()}`;

const industries = `${interiorHero("Industries", "Built for Organizations With Complex Decisions and Real Accountability.", "Quant Strata serves commercial, public, regulated, and mission-driven organizations that need both technical depth and practical business judgment.")}
  <section class="interior-section page-width"><div class="industry-grid">${[["Small & Midsize Businesses","Finance operations, forecasting, dashboards, and advisory support that help growing organizations build the discipline needed to scale."],["Nonprofits & Associations","Formation, exemption and annual filing support, governance policies, management reporting, impact measurement, and board-ready insight."],["Government & Public Sector","Performance analytics, economic research, program evaluation, geospatial analysis, and transparent reporting for public accountability."],["Government Contractors","Reporting infrastructure, financial controls, operational metrics, and compliance-readiness support for organizations serving public clients."],["Regulated Finance Teams","Finance transformation, data governance, planning, controls, and executive decision support in complex operating environments."],["Healthcare & Education","Access, demand, workforce, financial, and performance analysis for institutions accountable to diverse stakeholders."]].map(([title,copy],i)=>`<article class="industry-card"><span>0${i+1}</span><h2>${title}</h2><p>${copy}</p></article>`).join("")}</div></section>${closingCTA()}`;

const insights = `${interiorHero("Insights", "Useful Analysis for Leaders Responsible for the Next Decision.", "Quant Strata insights translate technical finance, analytics, and compliance topics into practical guidance for business and nonprofit leaders.")}
  <section class="interior-section page-width"><div class="interior-intro"><h2>An Evidence-Led Resource Library.</h2><div class="insight-intro"><p>We are organizing original articles, briefings, and practical guides around the questions our clients face most often. Published work will be clearly distinguished from client engagements and will not disclose confidential information.</p><div class="insight-note">This section is reserved for verified, publishable material so the website never implies client results that have not been documented and approved.</div></div></div>${cards([["Finance & Advisory","Practical guidance on management reporting, forecasting, accounting operations, controls, and financial decision-making."],["Analytics & Business Intelligence","Perspectives on dashboard design, KPI governance, modeling, automation, and communicating evidence to leadership."],["Nonprofit & Compliance","Clear explanations of formation, exemption applications, annual reporting, governance, and operational compliance."]])}</section>${closingCTA()}`;

const about = `${interiorHero("About", "Business Judgment, Analytical Rigor, and a Commitment to Useful Work.", "Quant Strata is a Philadelphia-based, veteran- and minority-owned advisory and analytics firm serving businesses, nonprofits, government entities, and institutional teams.")}
  <section class="interior-section page-width"><div class="interior-intro"><h2>Built to Connect Strategy With Execution.</h2><p>Organizations rarely struggle because they lack data. They struggle because financial processes, operating context, and analytical systems are disconnected. Quant Strata brings those disciplines together—helping leaders establish reliable information, interpret it correctly, and act with greater confidence.</p></div><div class="profile-strip"><div class="profile-monogram">QS</div><div><p class="eyebrow">Experience That Crosses Disciplines</p><h2>15+ Years Across Finance, Analytics, and Executive Decision Support.</h2><p>Quant Strata’s leadership experience includes FP&A, finance transformation, business intelligence, data integration, regulatory analytics, governance, and executive reporting.</p></div></div></section>
  <section class="interior-section tinted"><div class="page-width"><div class="interior-intro"><h2>Our Working Principles.</h2><p>Every engagement is grounded in clear scope, responsible professional boundaries, and practical transfer of knowledge to the client team.</p></div>${cards([["Clarity","Define the decision, deliverable, responsibilities, and limits of the engagement from the beginning."],["Rigor","Use traceable methods, documented assumptions, and evidence appropriate to the decision."],["Utility","Deliver work the client can understand, use, and maintain after the engagement."]])}</div></section>${closingCTA()}`;

const services = `${interiorHero("Services", "Advisory and Analytics, Designed to Work Together.", "Choose a focused service or combine capabilities into an integrated engagement spanning finance operations, compliance, planning, reporting, and advanced analysis.")}
  <section class="interior-section page-width"><div class="pathway-grid"><article class="pathway-card advisory-card"><p class="card-kicker">Business Advisory</p><h3>Build Stronger Financial Operations.</h3><p>Accounting support, management reporting, FP&A, controls, nonprofit compliance, and readiness services.</p><a href="../business-advisory/">View Business Advisory →</a></article><article class="pathway-card analytics-card"><p class="card-kicker">Analytics & Technology</p><h3>Make Complex Data Decision-Ready.</h3><p>Dashboards, modeling, automation, research, and integrated analytical systems for leadership.</p><a href="../analytics-technology/">View Analytics & Technology →</a></article></div></section>${closingCTA()}`;

const contact = `${interiorHero("Contact", "Let’s Discuss the Decision, Process, or Problem in Front of You.", "Share what your organization is working through. Quant Strata will respond candidly about fit, scope, and the practical next step.")}
  <section class="interior-section page-width"><div class="contact-layout"><div class="contact-details"><div><span>Email</span><strong>${emailLink}</strong></div><a href="tel:2152783518"><span>Phone</span><strong>(215) 278-3518</strong></a><div><span>Location</span><strong>Philadelphia, Pennsylvania</strong></div><div><span>Business Hours</span><strong>Monday–Friday, 9:00 am–5:00 pm</strong></div></div><div class="intake-card"><h2>Help Us Understand Your Need.</h2><p>For the most useful first conversation, include:</p><ul><li>Your Organization and Industry</li><li>The Advisory or Analytics Support You Are Considering</li><li>The Decision, Deadline, or Compliance Requirement Involved</li><li>The Systems, Data, or Documentation Currently Available</li><li>Your Preferred Timeframe for Beginning the Engagement</li></ul><a class="button button-primary page-cta" href="mailto:info@q-strata.com?subject=Quant%20Strata%20Consultation%20Request">Email Quant Strata →</a></div></div></section>`;

export const pages = [
  { route: "", title: "Quant Strata Business Advisory & Analytics", description: "Business advisory, finance and accounting operations, compliance support, dashboards, forecasting, and advanced analytics.", content: home, depth: 0 },
  { route: "services", title: "Services | Quant Strata", description: "Integrated Business Advisory and Analytics services.", content: services, depth: 1 },
  { route: "business-advisory", title: "Business Advisory | Quant Strata", description: "Accounting operations, FP&A, nonprofit compliance, controls, and finance support.", content: businessAdvisory, depth: 1 },
  { route: "analytics-technology", title: "Analytics & Technology | Quant Strata", description: "Executive dashboards, forecasting, data integration, automation, research, and GIS.", content: analytics, depth: 1 },
  { route: "industries", title: "Industries | Quant Strata", description: "Advisory and analytics for businesses, nonprofits, government, contractors, healthcare, and education.", content: industries, depth: 1 },
  { route: "insights", title: "Insights | Quant Strata", description: "Finance, analytics, and nonprofit compliance guidance for organizational leaders.", content: insights, depth: 1 },
  { route: "about", title: "About Quant Strata", description: "A Philadelphia-based, veteran- and minority-owned Business Advisory and Analytics firm.", content: about, depth: 1 },
  { route: "contact", title: "Contact Quant Strata", description: "Contact Quant Strata Business Advisory & Analytics in Philadelphia.", content: contact, depth: 1 },
];
